const data = {
  products: [
    {
      name: 'nike slim shirt',
      slug: 'nike-slim shirt',
      category: 'Shirt',
      Image: '/image/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirt',
      Image: '/image/p2.jpg',
      price: 220,
      countInStock: 12,
      brand: 'adidas',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'nike slim Pant',
      slug: 'nike-slim pant',
      category: 'Pants',
      Image: '/image/p3.jpg',
      price: 125,
      countInStock: 15,
      brand: 'nike',
      rating: 4.7,
      numReviews: 10,
      description: 'high quality pant',
    },
    {
      name: 'Addias slim pant',
      slug: 'adidas-slim pant',
      category: 'Shirt',
      Image: '/image/p4.jpg',
      price: 160,
      countInStock: 39,
      brand: 'adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pant',
    },
  ],
};

export default data;
